apiVersion: v1
kind: Service
metadata:
  name: corn
  labels:
    app: corn
spec:
  selector:
    app: corn
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: proxy
      port: 8090
      targetPort: 8090
  type: ClusterIP
