[program:corn-test]
command=/usr/bin/bash -c /home/ccbruce/trc/trc201/trc-201-ap-src/datahub-task/corn/bin/deploy/conf/conf.d/test.sh
directory=/home/ccbruce/trc/trc201/trc-201-ap-src/datahub-task/corn/bin/deploy/conf/conf.d/
autostart=true
autorestart=true
startsecs=3
stdout_logfile=/var/log/corn/stdout.log
stderr_logfile=/var/log/corn/stderr.log
stopsignal=TERM
